### ISSUE TITLE
Submissão de palestras para o meetup do dia 15/03

### ISSUE THREAD

**Issue by jpmsegurado** [frontendgoias/meetup-gojs#1]
Votem com um joinha nas palestras que mais te interessarem. Dia 08/03 fecha a votação e as 5 palestras mais bem votadas serão escolhidas.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by felipeands** [comment]
Felipe Andrada - Service Workers. Agora seu app roda offline

Já estamos acostumados a ver o javascript interagir com elementos da interface. Os service workers acrescentam uma nova camada a nossas aplicações, ali entre o navegador e as conexões web. 
Vou mostrar formas de aproveitar desses recursos da API para tornar nossas aplicações mais inteligentes. E de forma transparente para o usuário, melhorar sua experiência de uso.

**Comment by fabricionaweb** [comment]
Fabricio Augusto - Testes unitarios. Testar seu codigo vai te tornar um dev melhor.

É um fato comum desenvolvedores não entenderem as vantagens de testar seu código e/ou nem saber como fazer isso; eu ja fui um desses. Testar seu código significa exercer as menores partes dele para a falha e para o sucesso, provando a consistência dele para solucionar as responsabilidades atribuídas. Quando você domina testes, naturalmente não somente seu código mas também seu raciocínio se tornam melhores e você evolui. Nesta talk, eu serei seu guia.

**Comment by felipeands** [comment]
Felipe Andrada - Interagindo em redes ethereum com javascript

**Comment by bleidi** [comment]
Rafael 'bleidi' Souza - Webcomponents e as novidades do Polymer 3.0

Web components é parte da especificação da plataforma web para reutilização e encapsulamento de novas tags HTML customizadas. Seguindo o lema que a Google tem de "construa com a plataforma e não contra/apesar dela" vamos entender um pouco mais de como escrever um componente e tudo que a nova versão do framework da Google tem a nos oferecer.

**Comment by ghost** [comment]
Juliana Gaioso - Acessibilidade

Práticas para tornar a web mais inclusiva e acessivel para pessoas com variadas deficiências.

**Comment by diogobeda** [comment]
Diogo Beda - Brincando de gerar código JS

Será que conseguimos gerar uma aplicação à partir de alguma estrutura de dados arbitrária? Vou introduzir o conceito de ASTs e tentar fazer um live-coding gerando uma aplicação simples à partir de uma estrutura de dados.

**Comment by leandro** [comment]
Leandro Camargo - Programando de forma prática e minimalista

A idéia dessa talk é defender uma filosofia onde se escreve código com uma lógica menos preventiva, menos bullet proof (menos perfeccionista) e mais objetiva e direta ao ponto, em termos do que se é proposto na iteração/tarefa atual, visando um desenvolvimento de recursos/produtos mais incremental.
