### ISSUE TITLE
Submissão de palestras para o meetup do dia 23/01 - React

### ISSUE THREAD

**Issue by jpmsegurado** [frontendgoias/meetup-gojs#12]
Votem com um joinha nas palestras que mais te interessarem. Dia 15/01 fecha a votação e as mais bem votadas serão escolhidas até que se preencham os slots de tempo para palestras dentro da programação do meetup.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

O tema deste meetup será **React**.

**Comment by diogobeda** [comment]
Design de software aplicado a React

Não é incomum encontrar argumentos para o uso de React (e outras bibliotecas orientadas a componentes) que toquem no benefício de reaproveitar componentes na sua aplicação. Após me envolver com algumas dezenas de aplicações React, percebo que esse e outros viéses induzem vários desenvolvedores ao erro quando trabalham em codebases complexas e de grande porte.

Nessa palestra vou abordar a criação e manutenção de componentes React a partir de uma perspectiva de design de software, passando por princípios-guia, abstrações ou a falta delas, alto e baixo acoplamento e análise de trade-offs. Bem como exemplos e técnicas práticas para alcançar um bom design na sua aplicação React.

**Comment by bleidi** [comment]
React Fishbowl

Fishbowl (método aquário) é uma dinâmica de discussão em grupo que favorece a troca de experiências e permite que todos possam expressar seus pontos de vista. 

Nessa sessão, iremos abordar alguns dos temas mais recorrentes de design e implementação no ecossistema de React.

![Image of SpongeBob](https://i.ytimg.com/vi/rtQKP1we-Dk/maxresdefault.jpg)

**Comment by dnlsilva** [comment]
**Usar ou não usar Redux, eis a questão?**

Muitas são as duvidas e dificuldades quando se fala sobre o assunto, entretanto nessa talk iremos mostrar de forma pratica como usar a arquitetura Flux e quando implementar a mesma.
