### ISSUE TITLE
Submissão de palestras para o meetup do dia 19/04

### ISSUE THREAD

**Issue by jlcarvalho** [frontendgoias/meetup-gojs#3]
Votem com um joinha nas palestras que mais te interessarem. Dia 12/04 fecha a votação e as 4 palestras mais bem votadas serão escolhidas.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by jlcarvalho** [comment]
Jean Lucas de Carvalho - Bending Ionic Framework at your will

In this pep talk we'll talk about how we can overcome technical limitations of Ionic Framework in order to achieve the best result for our users.

**Comment by bleidi** [comment]
Rafael 'bleidi' Souza - Webcomponents e as novidades do Polymer 3.0

Web components é parte da especificação da plataforma web para reutilização e encapsulamento de novas tags HTML customizadas. Seguindo o lema que a Google tem de "construa com a plataforma e não contra/apesar dela" vamos entender um pouco mais de como escrever um componente e tudo que a nova versão do framework da Google tem a nos oferecer.

**Comment by gmtborges** [comment]
Gustavo Martins T Borges - Deploy em produção da sua SPA na AWS.

Nessa talk eu vou mostrar o passo a passo de como utilizar os serviços de storage, CDN e certificado TLS para subir seu site ou SPA em produção na AWS.
