### ISSUE TITLE
Submissão de palestras para o meetup do dia 17/05

### ISSUE THREAD

**Issue by bleidi** [frontendgoias/meetup-gojs#4]
Votem com um joinha nas palestras que mais te interessarem. Dia 10/05 fecha a votação e as mais bem votadas serão escolhidas até que se preencham os slots de tempo para palestras dentro da programação do meetup.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by arthurborgesdev** [comment]
Resin.io on [electrical] rails!!!

Você curte programação? Programa? É Desenvolvedor? Bora programar plaquinhas eletrônicas então?

10 em cada 10 desenvolvedores se assustam e fogem com essa última pergunta.Mas isso até agora. 

O mundo das plaquinhas pode ser mais divertido e fácil com resin.io. E isso porque você pode utilizar as linguagens que ama para interagir diretamente com elas!

Essa palestra é minha contribuição humilde, porém ambiciosa de trazer o universo de Resin.io para os desenvolvedores de Goiânia!

**Comment by felipeands** [comment]
Felipe Andrada - Integrando uma aplicação SPA com sockets numa API Rails

Uma hora você vai precisar estabelecer conexão com um servidor broadcast e eu vou mostrar um pouco do passo a passo para fazer essa comunicação em uma aplicação mobile javascript.

Pode ser útil quando precisamos manter a posição de markers atualizados em um mapa por exemplo...

**Comment by bleidi** [comment]
Juliana Gaioso - Acessibilidade

Práticas para tornar a web mais inclusiva e acessivel para pessoas com variadas deficiências.
