### ISSUE TITLE
Submissão de palestras para o meetup do dia 21/06

### ISSUE THREAD

**Issue by Bilusca** [frontendgoias/meetup-gojs#5]
Votem com um joinha nas palestras que mais te interessarem. Dia 14/06 fecha a votação e as mais bem votadas serão escolhidas até que se preencham os slots de tempo para palestras dentro da programação do meetup.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by victorivens05** [comment]
Victor Ivens - Cypress, testes com boa relação custo benefício

Nessa talk vou fazer uma breve apresentanção do Cypress, uma ferramenta de teste E2E, apresentar as principais formas de usá-lo com relação aos dados e às telas protegidas por login. Ao final uma conclusão sobre o custo benefício de testes E2E usando o cypress vs testes integrados.

**Comment by arthurborgesdev** [comment]
Arthur Borges - li (linguagem de intenções)

Pretendo apresentar `li`, uma forma de escrever que pode ser usada para expressar intenções de forma simples, clara e objetiva. No momento estou usando para escrever comentários nos meus códigos, mas como é open-source, pode ser usada para qualquer outra coisa que acharem interessante.

Repositório: https://github.com/arthurborgesdev/linguagem-intencoes

**Comment by rayansostenes** [comment]
Rayan Sóstenes - React Native: Por baixo dos panos


Nesta talk, vamos nos aprofundar nos detalhes técnicos sobre como o React Native funciona. Falaremos sobre a `bridge` assíncrona que serve como canal de comunicação entre o código JavaScript e a plataforma e como o React se encaixa nesse modelo.
