### ISSUE TITLE
Submissão de palestras para o meetup do dia 16/08

### ISSUE THREAD

**Issue by Bilusca** [frontendgoias/meetup-gojs#6]
Votem com um joinha nas palestras que mais te interessarem. Dia 14/06 fecha a votação e as mais bem votadas serão escolhidas até que se preencham os slots de tempo para palestras dentro da programação do meetup.

As palestras devem ser submetidas no seguinte formato:

[Nome] - [tema ou título da palestra]
[Descrição]

**Comment by jlcarvalho** [comment]
Jean Lucas de Carvalho - Carregamento progressivo de imagens

Nesta talk, vamos entender como usar o IntersectionObserver e estratégias de placeholders de imagens para conseguir atingir um carregamento progressivo de imagens semelhante ao usado por empresas como Medium e Facebook.

**Comment by jcserracampos** [comment]
Júlio Campos - Elm: O que é, como usar, por que usar
Elm tem começado a despontar como uma nova linguagem para front end. Nesta palestra, será apresentado um pouco sobre ela e como começar a usar.
